### ISSUE TITLE
Is this compatible with Wails V2 beta?

### ISSUE THREAD

**Issue by BillBuilt** [raitonoberu/wails-svelte-template#1]
Hello,

What I am running:
Go: 1.17.5
Node: 17.3.0
NPM:  8.3.0
Wails: 2.0.0-beta.27

I'm installing this via the recommended method using: 
`wails init -n myapp -t https://github.com/raitonoberu/wails-svelte-template -g`

Then going into `/myapp/frontend` and running:
`npm install`

Then opening a terminal in `/myapp` and running:
`wails dev`

Then in another terminal window in `/myapp/frontend` and running:
`npm run dev`

At this point, running `npm run dev` causes a panic in the first window:

`panic: Unexpected host for request on wails:// scheme
goroutine 7 [running]:
github.com/wailsapp/wails/v2/internal/frontend/desktop/darwin.(*Frontend).processRequest(0xc00019e840, 0xc0001e6210)
	/Users/billmatlock/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.27/internal/frontend/desktop/darwin/frontend.go:288 +0x2a5
github.com/wailsapp/wails/v2/internal/frontend/desktop/darwin.(*Frontend).startRequestProcessor(0x0)
	/Users/billmatlock/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.27/internal/frontend/desktop/darwin/frontend.go:105 +0x48
created by github.com/wailsapp/wails/v2/internal/frontend/desktop/darwin.NewFrontend
	/Users/billmatlock/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.27/internal/frontend/desktop/darwin/frontend.go:92 +0x2b1`

Not sure if this is a problem with the template or if this needs to be addressed at Wails

Thanks!

**Comment by raitonoberu** [comment]
Hello @Cure4Life and thanks for reporting.
I just tried all the steps above with Wails v2.0.0-beta.27 and it works without errors. This error seems to be platform-specific, but I don't have macos to reproduce it.
Does the default template or other custom templates (e.g. [react](https://github.com/flin7/wails-react-template)) work for you?

**Comment by BillBuilt** [comment]
Hi, thanks for the prompt reply...

I tried with your template, also the default Svelte template that is packaged in the Wails init command and both panicked in the same manner. I did try using the React template here: `https://github.com/flin7/wails-react-template`

It did NOT panic and worked as expected. But I did notice that when running `npm run dev` that it (React) did not appear to launch a server but just watched the files for changes, as it did not report any url to browse to.

Here is the output from my terminal when running `npm run dev` for the React template:

`➜  frontend git:(master) ✗ npm run dev`

`wails-react@1.0.0 dev
webpack --mode development --watch`

`assets by status 25.7 KiB [cached] 2 assets`
`assets by status 1.01 MiB [compared for emit]`
`  asset main.js 1.01 MiB [compared for emit] (name: main)`
`  asset index.html 121 bytes [compared for emit]`
`runtime modules 2.39 KiB 7 modules`
`modules by path ./node_modules/ 983 KiB`
`  modules by path ./node_modules/style-loader/dist/runtime/*.js 5.75 KiB 6 modules`
 ` modules by path ./node_modules/scheduler/ 26.3 KiB 4 modules`
 ` modules by path ./node_modules/css-loader/dist/runtime/*.js 2.91 KiB 3 modules`
 ` modules by path ./node_modules/react/ 70.6 KiB 2 modules`
 ` modules by path ./node_modules/react-dom/ 875 KiB 2 modules`
 ` ./node_modules/object-assign/index.js 2.06 KiB [built] [code generated]`
`modules by path ./src/ 4.7 KiB (javascript) 25.7 KiB (asset)`
`  javascript modules 4.62 KiB 3 modules`

**Comment by BillBuilt** [comment]
I should also note that I tried the default vanilla JS Wails template (in other words, no template) and it also worked as expected.

**Comment by raitonoberu** [comment]
> But I did notice that when running npm run dev that it (React) did not appear to launch a server but just watched the files for changes

If serving was a problem, the latest commit should fix the issue. I... should have removed it earlier...

**Comment by BillBuilt** [comment]
Hello,

Thanks again for trying. However it is still panicking with the same messages so I don't think that was the issue. If i get a chance later I can try in a VM using windows.

**Comment by leaanthony** [comment]
I'm currently moving house but when I get moved in I'll look at this issue.

**Comment by raitonoberu** [comment]
I assume this can be closed.
